### ISSUE TITLE
Create a demo site

### ISSUE THREAD

**Issue by ldez** [timhabermaas/stackmat.js#4]
I want to create a demo site with GitHub Pages.

You can activate this options in the settings panel:

![capture du 2017-03-01 20-44-36](https://cloud.githubusercontent.com/assets/5674651/23477969/0052d738-fec0-11e6-9801-b6e9786c5791.png)

To activate this options I need to create a `docs` folder.

**Comment by ldez** [comment]
@timhabermaas can you activate GitHub Pages ?

**Comment by timhabermaas** [comment]
@ldez Done: http://timhabermaas.github.io/stackmat.js/ I had to add an empty `docs/index.html` in order for it to work, though.

**Comment by ldez** [comment]
@timhabermaas can you put url to the front of repository ?

**Comment by timhabermaas** [comment]
Done.

**Comment by ldez** [comment]
Thanks!
