### ISSUE TITLE
Inconsistency in the README.md "Usage" section

### ISSUE THREAD

**Issue by ranolfi** [timhabermaas/stackmat.js#9]
Notice how the callback argument in line 4 is called `state`, but then in line 5 it's incorrectly referred to as `signal`.

> First, create a Stackmat.Timer object and pass in a callback function which gets called every time the timer sends a signal - around five times a second.
> 
> ```
> import { Stackmat } from 'stackmat.js';
> 
> const options = {
>   signalReceived(state) {
>     console.log("Current Time: " + signal.getTimeAsString())
>   }
> };
> 
> const timer = new Stackmat.Timer(options);
> ```

**Comment by ldez** [comment]
Thanks for your interest :smiley: 

Feel free to fix the documentation by doing a pull request.
